package file

import (
	"bytes"
	"log"
	"os"
	"os/exec"
	"text/template"
)

var fileTemplate = `// DO NOT EDIT THIS FILE. THIS FILE WAS AUTO GENERATED BY GOMBOK.
package {{.PackageName}}

{{- if len .ImportPkgs }}
import (
{{- range .ImportPkgs}}	"{{.}}"
{{- end}}
)
{{- end}}

{{.Content}}
`

type FileTemplateElement struct {
	PackageName string
	ImportPkgs  []string
	Content     string
}

func WriteFile(packageName string, importPkgs []string, content string, filepath string) error {
	tmpl, err := template.New("file").Parse(fileTemplate)
	if err != nil {
		return err
	}

	data := FileTemplateElement{
		PackageName: packageName,
		ImportPkgs:  importPkgs,
		Content:     content,
	}

	var buf bytes.Buffer

	err = tmpl.Execute(&buf, data)
	if err != nil {
		return err
	}

	err = os.WriteFile(filepath, buf.Bytes(), 0644)
	if err != nil {
		return err
	}

	cmd := exec.Command("goimports", "-w", filepath)
	if err := cmd.Run(); err != nil {
		log.Printf("Error formatting file %s: %v", filepath, err)
	}

	return nil
}
